name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  
jobs:
 build:
   runs-on: ubuntu-latest

   steps:
     - name: Checkout code
       uses: actions/checkout@v5

     - name: Set up Node.js
       uses: actions/setup-node@v5
       with:
          node-version: '22'

     - name: Start application 
       run: |
         node server.js &
         sleep 3

     - name: Test application
       run: |
        curl http://localhost:5000   

     - name: Build Docker image
       run: |
         docker build -t actioncalculator .   

     - name: Tagging Docker image
       run: |
        docker tag actioncalculator green123ree/calculator_app

     - name: Push docker image to docker hub
       run: |
        docker push green123ree/calculator_app        
             